name: Trigger Netify Build Hook
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main


jobs:
  deploy:
    name: Request Host Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{secrets.NETIFY_GIT_MAIN_HOOK}}